<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maks.TaskPlanner.DataAccess.Abstractions\Maks.TaskPlanner.DataAccess.Abstractions.csproj" />
    <ProjectReference Include="..\Maks.TaskPlanner.DataAccess\Maks.TaskPlanner.DataAccess.csproj" />
    <ProjectReference Include="..\Maks.TaskPlanner.Domain.Logic\Maks.TaskPlanner.Domain.Logic.csproj" />
    <ProjectReference Include="..\Maks.TaskPlanner.Domain.Models\Maks.TaskPlanner.Domain.Models.csproj" />
  </ItemGroup>

</Project>
